### PR TITLE
added traceability matrix

### PR DESCRIPTION
**Pull request by vtwigge1000**
Please review and make changes where necessary. Or let me know what I should fix or change. Thanks.

### CODE REVIEW

**Comment by Idrian** [comment]
VICTOR!!!!! I think you numbered the priorities wrong, I would have put Activity management as 2, Push notifications as 3 since it is a primary requirement in the specs and then account and admin as say 4-4 or 4-5 since someone can log in as a guess to the system and Admin I feel is only needed to keep everything intact, but it might function without it. I may be wrong with Admin tho but the rest I feel needs to change.
The use-cases themselves and how they are mapped look correct so it's only the priority that needs redoing.

**Comment by vtwigge1000** [comment]
@Idrian My reasoning for Admin being of priority 2 is that in our SRS document under Functional Requirements - Admin System 1.2 it says "The admin system will allow a designated administrator to add, remove and manage system, activity and event notifications". So I thought that because activity and notification creation and management depends on an Administrator, the Admin system will need to be implemented before the Activity and Notification Systems. I also realise now, that Account should be of lower priority than Activity and Notification, so I agree with you there.

From highest to lowest priority I think it should be Core Navigation, Admin, Activity, Notification, Account. Or do you still think Admin should also be lower than Activity and Notification?

**Comment by Idrian** [comment]
I agree with you there yes, now I just think that the certain use cases in admin might be of lower priority than stuff in admin so for instance everything doing with activities will have a higher use case priority than that of push notification but only the use cases the admin will still be of higher priority.

**Comment by vtwigge1000** [comment]
Okay cool, so basically if I understand you correctly, in total Activity and Notification is of higher priority than Admin, although Admin have minor cases where priority is higher. So are you happy with the following order - Navigation, Activity, Notification, Admin and then Account? Or do you think Admin and Account should switch?

**Comment by Idrian** [comment]
Yes that seems correct how you want to do it

**Comment by vtwigge1000** [comment]
Please check if you guys are happy with the updated Traceability Matrix

**Pull request merged**
